<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>tpl</string>
		</array>

		<key>name</key>
		<string>Dle</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>include</key>
				<string>#comments</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#blocks</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#inline</string>
			</dict>
			<dict>
				<key>include</key>
				<string>text.html.basic</string>
			</dict>
		</array>
		<key>repository</key>
		<dict>
			<key>blocks</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>(\[/?)([a-zA-Z0-9:_-]+)</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.tag.begin.dle</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>entity.name.tag.other.dle</string>
							</dict>
						</dict>
						<key>end</key>
						<string>(\])</string>
						<key>endCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.tag.end.dle</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>
									punctuation.definition.tag.begin.dle meta.scope.between-tag-pair.dle
								</string>
							</dict>
							<key>3</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.tag.begin.dle</string>
							</dict>
							<key>4</key>
							<dict>
								<key>name</key>
								<string>entity.name.tag.dle</string>
							</dict>
							<key>5</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.tag.end.dle</string>
							</dict>
						</dict>
						<key>name</key>
						<string>meta.tag.other.dle</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#tag-stuff</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>

			<key>comments</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>(\{%?)\*</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.comment.dle</string>
							</dict>
						</dict>
						<key>end</key>
						<string>\*(%?\})</string>
						<key>name</key>
						<string>comment.block.dle</string>
						<key>patterns</key>
						<array/>
					</dict>
				</array>
			</dict>

			<key>inline</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>(\{/?)([a-zA-Z0-9:_-]+)</string>
						<key>beginCaptures</key>
						<dict></dict>
						<key>end</key>
						<string>(\})</string>
						<key>name</key>
						<string>punctuation.definition.variable.dle</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#tag-generic-attribute</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#string-double-quoted</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#string-single-quoted</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>

			<key>tag-stuff</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#tag-generic-attribute</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#string-double-quoted</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#string-single-quoted</string>
					</dict>
				</array>
			</dict>

			<key>tag-generic-attribute</key>
			<dict>
				<key>match</key>
				<string>\b([a-zA-Z\-\_:]+)</string>
				<key>name</key>
				<string>entity.other.attribute-name.dle</string>
			</dict>

			<key>string-double-quoted</key>
			<dict>
				<key>begin</key>
				<string>"</string>
				<key>beginCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.begin.dle</string>
					</dict>
				</dict>
				<key>end</key>
				<string>"</string>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.end.dle</string>
					</dict>
				</dict>
				<key>name</key>
				<string>string.quoted.double.dle</string>
				<key>patterns</key>
				<array/>
			</dict>

		</dict>
		<key>scopeName</key>
		<string>text.html.dle</string>
		<key>uuid</key>
		<string>b61a7501-3758-48ee-bbec-a3bba011e530</string>
	</dict>
</plist>